# Generated by Django 5.2 on 2025-05-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinedo',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
