# Generated by Django 5.2 on 2025-05-21 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empleado', '0002_alter_vinedo_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vinedo',
            old_name='id_libro',
            new_name='id',
        ),
    ]
