# Generated by Django 5.2 on 2025-05-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vinedo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.TextField()),
                ('hectareas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('variedad_uva', models.CharField(max_length=100)),
                ('anio_plantacion', models.IntegerField()),
            ],
        ),
    ]
