# Generated by Django 5.2 on 2025-05-22 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empleado', '0004_empleado_delete_vinedo'),
        ('Vinedo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muestreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('resultados', models.TextField()),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleado.empleado')),
                ('vinedo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vinedo.vinedo')),
            ],
        ),
    ]
